date: "2025-04-01"
download_ohlcv: false
cal_coint_corr: false
sentiment: false
test_all: null # true, false, null
plot_graph: true

# Entry, exit and trades generation
entry_signal: "senti_entry"
exit_signal: "senti_exit"
trades_method: "senti_trades"

# Sentiment analysis
news_ticker_list:
  - "AAPL"
  - "NVDA"
  - "MSFT"
  - "AMZN"
  - "GOOGL"
  - "META"
  - "TSLA"
  - "JPM"
  - "JNJ"
  - "V"
  - "XOM"
  - "UNH"
  - "WMT"
  - "PG"
  - "HD"
  - "NFLX"
  - "CRM"
  - "BAC"
  - "BA"
periods:
  - 1
  - 3
  - 5

# Download S&P500 tickers
snp500_url: "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
ignore_list:
  - "BRK.B"
  - "BF.B"
  - "CTAS"
  - "LEN"

# Download OHLCV
ohlcv:
  start_date: "2020-01-01"
  batch_size: 20
  stock_dir: "${path.stock_dir}"

# Compute Cointegration/Correlation
coint_corr:
  periods: "${periods}"
  corr_fn_list:
    - "pearsonr"
    - "spearmanr"
    - "kendalltau"

# Perform sentiment rating
senti:
  base_url: "https://finance.yahoo.com/quote/ticker/news)"
  news_ticker_list: "${news_ticker_list}"
  max_scrolls: 20
  model_list:
    - "ProsusAI/finbert"
    - "yiyanghkust/finbert-tone"
    - "ZiweiChen/FinBERT-FOMC"
    - "AventIQ-AI/finbert-sentiment-analysis"
  data_dir: "${path.data_dir}"

# Plot Strategies
plot_strat:
  full: "${full}"
  drilldown_mapping:
    entry_type: "Entry Strategy"
    entry_struct: "Entry Method"
    exit_struct: "Exit Method"
    stop_method: "Stop Loss Method"
    hf_model: "FinBERT Model"
    coint_corr_fn: "Cointegration / Correlation Function"
    period: "Time Period"
  periods: "${periods}"
  min_trading_period: 2
  analysis_cols:
    - "annualized_return"
    - "win_rate"
    - "total_num_trades"
    - "highest_neg_percent_return"
  top_n: 15
  top_n_common: 10
  palette: "dark" # https://seaborn.pydata.org/tutorial/color_palettes.html
  disp_cols: 
    - "ticker_pair"
    - "overall_daily_ret"
    - "trading_period"
    - "win_rate"
    - "win_count"
    - "days_held_max"
    - "neg_ret_mean"
    - "neg_ret_max"
    
# Path
path:
  # directory path
  data_dir: "./data"
  stock_dir: "${path.data_dir}/stock"
  coint_corr_dir: "${path.data_dir}/coint_corr"
  graph_dir: "${path.data_dir}/graph"
  strategy_dir: "src/strategy"

  # file path
  entry_signal_path: "${path.strategy_dir}/entry/${entry_signal}.py"
  exit_signal_path: "${path.strategy_dir}/exit/${exit_signal}.py"
  trades_path: "${path.strategy_dir}/trade/${trades_method}.py"
  entry_struct_path: "${path.strategy_dir}/base/entry_struct.py"
  exit_struct_path: "${path.strategy_dir}/base/exit_struct.py"
  stop_method_path: "${path.strategy_dir}/base/cal_exit_price.py"

# Standard parameters to initialize 'GenPriceAction'
std:
  path: "${path}"
  entry_signal: "${entry_signal}"
  exit_signal: "${exit_signal}"
  trades_method: "${trades_method}"
  num_lots: 10
  req_cols:
    - "date"
    - "high"
    - "low"
    - "close"
    - "entry_signal"
    - "exit_signal"
  monitor_close: true
  percent_loss: 0.05
  top_n: 10

# Run single test
single:
  entry_type: "long" # long, short, longshort
  entry_struct: "multiple" # multiple, multiple_half, single
  exit_struct: "take_all" # fifo, lifo, half_fifo, half_lifo, take_all
  stop_method: "no_stop" # percent_loss, nearest_loss, latest_loss
  hf_model: "prosusai" # prosusai, ziweichen, yiyanghkust, aventiq_ai
  coint_corr_fn: "kendalltau" # pearsonr, spearmanr, kendalltau, conint
  period: 5

# Run full test
stop:
  - "no_stop"
  - "percent_loss"
  - "nearest_loss"
  - "latest_loss"
hf_model:
  - "prosusai"
  - "yiyanghkust"
  - "ziweichen"
  - "aventiq_ai"
coint_corr_fn:
  - "coint"
  - "pearsonr"
  - "spearmanr"
  - "kendalltau"
period:
  - 1
  - 3
  - 5

full:
  # long and short strategy (excluding single entry)
  - - - "long"
      - "short"
    - - "multiple"
      - "multiple_half"
    - - "fifo"
      - "lifo"
      - "half_fifo"
      - "half_lifo"
      - "take_all"
    - "${stop}"
    - "${hf_model}"
    - "${coint_corr_fn}"
    - "${period}"

  # single entry for long and short strategy
  - - - "long"
      - "short"
    - - "single"
    - - "fifo"
      - "half_fifo"
    - "${stop}"
    - "${hf_model}"
    - "${coint_corr_fn}"
    - "${period}"
    
  # long-short strategy
  - - - "longshort"
    - - "multiple"
      - "multiple_half"
      - "single"
    - - "take_all"
    - "${stop}"
    - "${hf_model}"
    - "${coint_corr_fn}"
    - "${period}"